### PR TITLE
Add SIGPolicy website link to home page

### PR DESCRIPTION
**Pull request by pranavrajpal**
SIGPolicy has a website now, so add a link to the SIGPolicy website to the home page.

### CODE REVIEW

**Review by jlevine18 — APPROVED** [review]
LGTM

**Review by devksingh4 — CHANGES_REQUESTED** [review]
@pranavrajpal Cloudflare validation build failed to trigger for some reason - please close and recreate PR - shouldn't be an issue on your end but just want to double-check all is OK. Thanks.

**Comment by pranavrajpal** [comment]
Do you mean closing and reopening the PR (like I did above) or did you want me to create an entirely different PR?

**Comment by jlevine18** [comment]
We just need to trigger a new build to ensure that CF doesn't find
any issues. This should be able to be done by pushing any commit or opening
a new PR with the same branch, AFAIK.

**Comment by pranavrajpal** [comment]
Ok so it doesn't look like force pushing a modified commit to the same branch triggers the Cloudflare Pages workflow.

Do any of you know where I can see what your Cloudflare Pages configuration/setup looks like to see if I can try debugging this? The "View Logs" links on some other PRs give me a "Project not found" error on Cloudflare so I'm guessing that means I'm missing some Cloudflare-related permissions that would let me see said logs.

**Comment by jlevine18** [comment]
Oh, I know what the problem is: we can't build from a branch outside of acm-uiuc. Will merge over and remake the PR. Will also add you to infra so you have edit perms in the future (for all non-master branches)

**Pull request merged**
