### PR TITLE
Add newsletter popup menu for desktop

### PR DESCRIPTION
**Pull request by JCalago02**
Add newsletter popup menu for desktop which is visible on the home page (only on desktop). 

Popup contains a link to the newsletter, description, and an exit button. The popup also automatically hides itself after scrolling into the sig-section.

### CODE REVIEW

**Comment by AydanPirani** [comment]
@JCalago02  thanks for working on this - it looks great when i test it out on my computer!

out of curiosity, did you do anything for the mobile site? the preview doesn't render correctly on my phone, and i can't tell if this is intended or my phone is glitching? (running msft edge on iphone)

**Comment by devksingh4** [comment]
I think that x-ing out of the newsletter prompt should result in the popup not showing for, say, a week. Otherwise every time someone visits the ACM site they have to x-out (which may not be that many times so its not necessarily a blocker, but perhaps something that should be addressed).

**Comment by devksingh4** [comment]
> @JCalago02 thanks for working on this - it looks great when i test it out on my computer!
> 
> out of curiosity, did you do anything for the mobile site? the preview doesn't render correctly on my phone, and i can't tell if this is intended or my phone is glitching? (running msft edge on iphone)

Also not seeing anything on the mobile simulation in Chrome for Windows.

**Comment by JCalago02** [comment]
I discussed with Labdhi, and the intention was to have this popup only display on desktop (which I believe is what is happening? If not I can take another look). 

To accommodate for mobile, we also decided to just add a button next to the buttons for instagram and discord which acts as a link to the newsletter, should be cleaner and easier to not cover any information on mobile. 

I'm still working on adding said button, but I'll also take a look into using cookies to disable the popup for frequent visitors.

**Comment by JCalago02** [comment]
The above changes are as follows:

- Newsletter icon button next to the discord now only loads on mobile views
- Desktop popup notification has a more defined exit button

**Comment by MattGeimer** [comment]
Looks like the button to close the popup is empty right now. Is this intended behavior? Also, thoughts on moving that button the the top right of the popup?

Screenshot 2023-03-19 at 11 05 25 AM

**Comment by JCalago02** [comment]
That screenshot is not the intended behavior for the popup. I checked both locally and on the Cloudflare Pages Preview URL with different browsers (chrome and edge), and for different resolutions, and I'm not able to replicate your screenshot. Any ideas on what could be causing this difference?


image

**Comment by MattGeimer** [comment]
I use Safari 😆

**Comment by AydanPirani** [comment]
@nunu2021  @MattGeimer  @devksingh4  Pinging for visibility! Is this good to merge now?

**Review by MattGeimer — APPROVED** [review]
LGTM 😎

**Review by Heasummn — APPROVED** [review]

**Pull request merged**
