### PR TITLE
Rewrite to Next.js from CRA (#108)

### PR DESCRIPTION
**Pull request by jlevine18**
* Rewrite to Next.js

* Fix file capitalization

### CODE REVIEW

**Comment by jlevine18** [comment]
TYSM @WhiteHoodHacker for doing this- looks great. I'm not entirely sure why our CF build fails- @devksingh4, do you have any ideas?

**Review by devksingh4 — CHANGES_REQUESTED** [review]
As discussed on discord:
Use dynamic routing to support `/event/[id]` paradigm instead of `/event?id=[id]` URLs.
Setup next.js edge worker support so we can host on Cloudflare Pages while still using dynamic features (this also enables us to one-click compression and other nice comforts later down the line).

**Comment by devksingh4** [comment]
> Oh, I'm very dumb and didn't realize that there needed to be changes to actions. This is why you don't do things at 7AM so that you can feel productive when you are woken up by yet _another_ ceiling leak in your Smile apartment.

The reason for this was actually that cf expected the output to be in `built` not `out`. Fixed next.config.js to output to `built`.

**Comment by devksingh4** [comment]
> #### ⚠️ GitGuardian has uncovered 1 secret following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secret in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

Not actually a secret.

**Review by devksingh4 — APPROVED** [review]

**Comment by WhiteHoodHacker** [comment]
> > Oh, I'm very dumb and didn't realize that there needed to be changes to actions. This is why you don't do things at 7AM so that you can feel productive when you are woken up by yet _another_ ceiling leak in your Smile apartment.
> 
> 
> 
> The reason for this was actually that cf expected the output to be in `built` not `out`. Fixed next.config.js to output to `built`.

That fix does not actually work. This is for dev output. You can no longer change the output directory.

**Comment by devksingh4** [comment]
> > > Oh, I'm very dumb and didn't realize that there needed to be changes to actions. This is why you don't do things at 7AM so that you can feel productive when you are woken up by yet _another_ ceiling leak in your Smile apartment.
> > 
> > 
> > The reason for this was actually that cf expected the output to be in `built` not `out`. Fixed next.config.js to output to `built`.
> 
> That fix does not actually work. This is for dev output cache (`.next`) folder. You can no longer change the output directory from `out`.

That fix is currently working in prod (www.acm.illinois.edu).

**Comment by WhiteHoodHacker** [comment]
Ok, `serve` script in `package.json` needs to be updated to `serve build` too.

**Pull request merged**
