### PR TITLE
Add paid event config

### PR DESCRIPTION
**Pull request by jlevine18**
Remade the PR per @AydanPirani 's request so that a cloudflare build is triggered

### CODE REVIEW

**Review by AydanPirani — CHANGES_REQUESTED** [review]
Thanks for working on this!

Couple of little things:

1) The payment page shows Membership in the top bar, as opposed to something more fitting - something along the lines of "Bar Crawl 2023" should be just fine (maybe pull from the JSON in the long run)?
image

2) This doesn't look great on mobile (reported by @MattGeimer ) - might just be the best move to remove the differing prices, and simply leave it as "Purchase Now!".

image


Thoughts would be nice - once we fix this, should be good to merge post Labdhi's confirmation :)

**Comment by devksingh4** [comment]
Made a few changes to the UX (signal when the page is processing information, clarify error messages, and make the paid modal clearer). Pending review from @nunu2021 but otherwise LGTM.

**Review by AydanPirani — CHANGES_REQUESTED** [review]
Everything LGTM, just waiting on final social confirmation before approving!

**Comment by AydanPirani** [comment]
lgtm - thanks so much for working on this and getting the iterations in! really do appreciate it :)

**Review by AydanPirani — APPROVED** [review]

**Comment by AydanPirani** [comment]
one thing, though - before you merge, please do make sure to disable registration. thanks in advance!!! :)

**Review by devksingh4 — APPROVED** [review]

**Pull request merged**
