### PR TITLE
add sigpolicy and sigarch cards to home page

### PR DESCRIPTION
**Pull request by akrakman**

### CODE REVIEW

**Comment by akrakman** [comment]
oh whoops the package lock

**Comment by Heasummn** [comment]
Also the yarn.lock. While you're at it, can you rebase those so that it's only one commit (it's okay if you're not sure how to do this)?

**Comment by akrakman** [comment]
yeah idk how to do that. Isn't everything on the same branch?

**Comment by akrakman** [comment]
oh shoot we're keeping the yarn-lock

**Comment by devksingh4** [comment]
Closing as out-of-date

**Pull request closed without merging**
